allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@google/genai"
  - esbuild
  - protobufjs
  - sharp
  - tesseract.js
  - unrs-resolver
